-- Tabela de VISITA da landing: o denominador.
--
-- Até 22/09/2026 o projeto contava CADASTRO (`leads`) e não contava visita
-- nenhuma. Sem saber quanta gente entra na página não existe taxa de conversão
-- visita→cadastro — e sem taxa, nenhuma mudança na landing pode ser provada
-- boa ou ruim, nem antes nem depois. Esta tabela é esse denominador.
--
-- Por que aqui e não no Analytics do Vercel: a mesma página é servida por DUAS
-- hospedagens (o projeto `alertastech-landing` no Vercel e o espelho em
-- gilmadson.github.io/alertas-tech/), e as duas recebem gente de verdade. Uma
-- medida que só vê o Vercel fica cega para metade da casa. Aqui o numerador
-- (`leads`) e o denominador (`visitas`) ficam no MESMO banco, com os mesmos
-- campos de origem: a taxa por campanha é uma consulta, não duas telas.
--
-- Segurança: mesmo desenho da `leads`. A chave `anon` é pública por desenho
-- (vai no HTML de qualquer jeito), então a policy deixa INSERIR e não deixa
-- LER. Sem dado pessoal: nem nome, nem e-mail, nem telefone, nem IP — não há
-- pessoa para identificar aqui, e por isso não há consentimento a pedir.
--
-- Como aplicar (uma vez, no projeto jfuqmjbxzhoceycauhys):
--   Supabase → SQL Editor → cola este arquivo → Run.
-- Enquanto não for aplicado, o POST da landing devolve 404 e a visita apenas
-- não é contada: o cadastro segue funcionando igual.

create table if not exists public.visitas (
  id          bigint generated by default as identity primary key,
  criado_em   timestamptz not null default now(),
  pagina      text not null,
  hospedagem  text,
  origem      text,
  meio        text,
  campanha    text
);

-- O relatório é sempre "por período": sem índice, contar o mês passado vira
-- varredura da tabela inteira quando ela crescer.
create index if not exists visitas_criado_em_idx
  on public.visitas (criado_em desc);

alter table public.visitas enable row level security;

-- Inserir, e só. Quem LÊ é o SQL Editor / a chave de serviço, nunca a página.
drop policy if exists "visita anonima pode inserir" on public.visitas;
create policy "visita anonima pode inserir"
  on public.visitas
  for insert
  to anon
  with check (true);
